hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

bye_the_world:
    path:     /byebye-world
    defaults: { _controller: OCPlatformBundle:Advert:bye }